In [59]:
#O critério de segmentação por cliente que faz sentido para o teste A/B em análise é pelo critério minimum_order_value
#O objetivo é analisar se houve aumento significativo em alguma das faixas de valores com o uso de cupons nos restaurantes ativos
#As faixas de valores são: '0-30', '30-60', '60-100', '100-200', '200+'

In [60]:
import pandas as pd
import plotly.express as px

In [61]:
#Lendo a tabela order_clean
orders_clean = pd.read_parquet("../data/order_clean.parquet")
display(orders_clean.head())
display(orders_clean.info())

#Lendo a tabela restaurant_clean
restaurant_clean = pd.read_parquet("../data/restaurant_clean.parquet")
display(restaurant_clean.head())
display(restaurant_clean.info())

#Lendo a tabela consumer_merge
consumer_merge = pd.read_parquet("../data/consumer_merge.parquet")
display(consumer_merge.head())
display(consumer_merge.info())

,customer_id,delivery_address_state,merchant_id,order_created_at,ano_mes_created_at,order_id,order_scheduled,order_total_amount,origin_platform,order_scheduled_date,ano_mes_scheduled_date
0,7ba88a68bb2a3504c6bd37a707af57a0b8d6e110a551c7...,SP,a992a079a651e699d9149423761df2427c0e3af0a2a1b5...,2019-01-17 22:50:06+00:00,2019-01,33e0612d62e5eb42aba15b58413137e441fbe906de2feb...,False,46.0,ANDROID,NaT,NaT
1,078acecdcf7fa89d356bfa349f14a8219db1ee161ce28a...,SP,5152f28ee0518b8803ccf0a4096eb2ff8b81e9491861c9...,2019-01-17 17:51:26+00:00,2019-01,148c4353a2952f3fe7973547283265eb22b575fb712ed2...,False,104.5,ANDROID,NaT,NaT
2,0e38a3237b5946e8ab2367b4f1a3ae6e77f1e215bc760c...,SP,b6096419455c35d06105a5ef0d25c51f9dd40e1e99ac33...,2019-01-17 22:53:47+00:00,2019-01,c37e495a91b498bb7b70a9e09ac115d0cdd443f152dc11...,False,35.0,IOS,NaT,NaT
3,cab1a004b7206d07910092c515a79834fea0a03d7d9054...,SP,082bfdcdf6ccdc343e3c4d25ee376b5b6ca7e96ad8b04e...,2019-01-17 23:56:53+00:00,2019-01,b4df94142d21354611247da9ca94f870c09b93989b531a...,False,40.8,IOS,NaT,NaT
4,aa7edf5b166b8c843aec3b96dc561222888734f3879123...,ES,d7adb764bac29ccb77fb8f746ffbd531bf05ec30a7e130...,2019-01-17 23:40:53+00:00,2019-01,4ff64b33b272c1886df21b63272220af6a82d1667dba70...,False,48.5,ANDROID,NaT,NaT

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3662321 entries, 0 to 3662320
Data columns (total 11 columns):
 #   Column                  Dtype
---  ------                  -----
 0   customer_id             object
 1   delivery_address_state  object
 2   merchant_id             object
 3   order_created_at        datetime64[ns, UTC]
 4   ano_mes_created_at      period[M]
 5   order_id                object
 6   order_scheduled         bool
 7   order_total_amount      float64
 8   origin_platform         object
 9   order_scheduled_date    datetime64[ns, UTC]
 10  ano_mes_scheduled_date  period[M]
dtypes: bool(1), datetime64[ns, UTC](2), float64(1), object(5), period[M](2)
memory usage: 282.9+ MB

None

,id,created_at,ano_mes,enabled,price_range,average_ticket,delivery_time,minimum_order_value,merchant_state
0,d19ff6fca6288939bff073ad0a119d25c0365c407e9e5d...,2018-04-05 14:49:18.165000+00:00,2018-04,False,3,60.0,50.0,30.0,SP
1,631df0985fdbbaf27b9b031a8f381924e3483833385748...,2018-01-14 21:40:02.141000+00:00,2018-01,True,3,60.0,0.0,30.0,SP
2,135c5c4ae4c1ec1fdc23e8c649f313e39be8db913d8bc5...,2018-01-07 03:47:15.554000+00:00,2018-01,True,5,100.0,45.0,10.0,RJ
3,d26f84c470451f752bef036c55517b6d9950d41806f10e...,2018-01-10 22:17:08.160000+00:00,2018-01,True,3,80.0,0.0,18.9,BA
4,97b9884600ea7192314580d9115f8882b8634f5aa201ff...,2018-04-06 00:16:20.935000+00:00,2018-04,True,3,60.0,0.0,25.0,SP

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7292 entries, 0 to 7291
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   7292 non-null   object
 1   created_at           7292 non-null   datetime64[ns, UTC]
 2   ano_mes              7292 non-null   period[M]
 3   enabled              7292 non-null   bool
 4   price_range          7292 non-null   int64
 5   average_ticket       7292 non-null   float64
 6   delivery_time        7291 non-null   float64
 7   minimum_order_value  7197 non-null   float64
 8   merchant_state       7292 non-null   object
dtypes: bool(1), datetime64[ns, UTC](1), float64(3), int64(1), object(2), period[M](1)
memory usage: 463.0+ KB

None

                                         customer_id is_target active
0  755e1fa18f25caec5edffb188b13fd844b2af8cf5adedc...    target   True
1  b821aa8372b8e5b82cdc283742757df8c45eecdd72adf4...   control   True
2  d425d6ee4c9d4e211b71da8fc60bf6c5336b2ea9af9cc0...   control   True
3  6a7089eea0a5dc294fbccd4fa24d0d84a90c1cc12e829c...    target   True
4  dad6b7e222bab31c0332b0ccd9fa5dbd147008facd268f...   control   True

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 806466 entries, 0 to 806465
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   customer_id  806466 non-null  object
 1   is_target    806466 non-null  object
 2   active       806156 non-null  object
dtypes: object(3)
memory usage: 18.5+ MB

None

In [62]:
#Filtrando apenas pedidos de restaurantes ativos
restaurant_ativos = restaurant_clean[restaurant_clean['enabled'] == True]

In [63]:
#Fazendo o merge entre as tabelas order_clean e consumer_merge para trazer a coluna is_target
order_target = orders_clean.merge(consumer_merge[['customer_id', 'is_target']], on='customer_id', how='left')
display(order_target.head())
display(order_target.info())

,customer_id,delivery_address_state,merchant_id,order_created_at,ano_mes_created_at,order_id,order_scheduled,order_total_amount,origin_platform,order_scheduled_date,ano_mes_scheduled_date,is_target
0,7ba88a68bb2a3504c6bd37a707af57a0b8d6e110a551c7...,SP,a992a079a651e699d9149423761df2427c0e3af0a2a1b5...,2019-01-17 22:50:06+00:00,2019-01,33e0612d62e5eb42aba15b58413137e441fbe906de2feb...,False,46.0,ANDROID,NaT,NaT,control
1,078acecdcf7fa89d356bfa349f14a8219db1ee161ce28a...,SP,5152f28ee0518b8803ccf0a4096eb2ff8b81e9491861c9...,2019-01-17 17:51:26+00:00,2019-01,148c4353a2952f3fe7973547283265eb22b575fb712ed2...,False,104.5,ANDROID,NaT,NaT,control
2,0e38a3237b5946e8ab2367b4f1a3ae6e77f1e215bc760c...,SP,b6096419455c35d06105a5ef0d25c51f9dd40e1e99ac33...,2019-01-17 22:53:47+00:00,2019-01,c37e495a91b498bb7b70a9e09ac115d0cdd443f152dc11...,False,35.0,IOS,NaT,NaT,control
3,cab1a004b7206d07910092c515a79834fea0a03d7d9054...,SP,082bfdcdf6ccdc343e3c4d25ee376b5b6ca7e96ad8b04e...,2019-01-17 23:56:53+00:00,2019-01,b4df94142d21354611247da9ca94f870c09b93989b531a...,False,40.8,IOS,NaT,NaT,control
4,aa7edf5b166b8c843aec3b96dc561222888734f3879123...,ES,d7adb764bac29ccb77fb8f746ffbd531bf05ec30a7e130...,2019-01-17 23:40:53+00:00,2019-01,4ff64b33b272c1886df21b63272220af6a82d1667dba70...,False,48.5,ANDROID,NaT,NaT,target

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3662321 entries, 0 to 3662320
Data columns (total 12 columns):
 #   Column                  Dtype
---  ------                  -----
 0   customer_id             object
 1   delivery_address_state  object
 2   merchant_id             object
 3   order_created_at        datetime64[ns, UTC]
 4   ano_mes_created_at      period[M]
 5   order_id                object
 6   order_scheduled         bool
 7   order_total_amount      float64
 8   origin_platform         object
 9   order_scheduled_date    datetime64[ns, UTC]
 10  ano_mes_scheduled_date  period[M]
 11  is_target               object
dtypes: bool(1), datetime64[ns, UTC](2), float64(1), object(6), period[M](2)
memory usage: 310.8+ MB

None

In [64]:
#Fazendo o merge entre as tabelas order_target e restaurant_ativos para trazer a coluna minimum_order_value
order_rest = order_target.merge(restaurant_ativos[['id', 'minimum_order_value']], left_on='merchant_id', right_on='id', how='left')
order_rest = order_rest[order_rest['minimum_order_value'].notnull()]
display(order_rest.head())
display(order_rest.info())

,customer_id,delivery_address_state,merchant_id,order_created_at,ano_mes_created_at,order_id,order_scheduled,order_total_amount,origin_platform,order_scheduled_date,ano_mes_scheduled_date,is_target,id,minimum_order_value
1,078acecdcf7fa89d356bfa349f14a8219db1ee161ce28a...,SP,5152f28ee0518b8803ccf0a4096eb2ff8b81e9491861c9...,2019-01-17 17:51:26+00:00,2019-01,148c4353a2952f3fe7973547283265eb22b575fb712ed2...,False,104.5,ANDROID,NaT,NaT,control,5152f28ee0518b8803ccf0a4096eb2ff8b81e9491861c9...,20.0
2,0e38a3237b5946e8ab2367b4f1a3ae6e77f1e215bc760c...,SP,b6096419455c35d06105a5ef0d25c51f9dd40e1e99ac33...,2019-01-17 22:53:47+00:00,2019-01,c37e495a91b498bb7b70a9e09ac115d0cdd443f152dc11...,False,35.0,IOS,NaT,NaT,control,b6096419455c35d06105a5ef0d25c51f9dd40e1e99ac33...,20.0
3,cab1a004b7206d07910092c515a79834fea0a03d7d9054...,SP,082bfdcdf6ccdc343e3c4d25ee376b5b6ca7e96ad8b04e...,2019-01-17 23:56:53+00:00,2019-01,b4df94142d21354611247da9ca94f870c09b93989b531a...,False,40.8,IOS,NaT,NaT,control,082bfdcdf6ccdc343e3c4d25ee376b5b6ca7e96ad8b04e...,10.0
4,aa7edf5b166b8c843aec3b96dc561222888734f3879123...,ES,d7adb764bac29ccb77fb8f746ffbd531bf05ec30a7e130...,2019-01-17 23:40:53+00:00,2019-01,4ff64b33b272c1886df21b63272220af6a82d1667dba70...,False,48.5,ANDROID,NaT,NaT,target,d7adb764bac29ccb77fb8f746ffbd531bf05ec30a7e130...,20.0
5,ad7ddcda2f57003170b8430f2b157c61fb63297bb8622e...,SP,c5c5fc3985020b3f637495e7d71828e2217e2035618e3e...,2019-01-17 23:54:27+00:00,2019-01,84a9eff359a75fcd34066186d2cd5ec128ebbed47a639c...,False,84.0,IOS,NaT,NaT,target,c5c5fc3985020b3f637495e7d71828e2217e2035618e3e...,0.0

<class 'pandas.core.frame.DataFrame'>
Index: 2563677 entries, 1 to 3662320
Data columns (total 14 columns):
 #   Column                  Dtype
---  ------                  -----
 0   customer_id             object
 1   delivery_address_state  object
 2   merchant_id             object
 3   order_created_at        datetime64[ns, UTC]
 4   ano_mes_created_at      period[M]
 5   order_id                object
 6   order_scheduled         bool
 7   order_total_amount      float64
 8   origin_platform         object
 9   order_scheduled_date    datetime64[ns, UTC]
 10  ano_mes_scheduled_date  period[M]
 11  is_target               object
 12  id                      object
 13  minimum_order_value     float64
dtypes: bool(1), datetime64[ns, UTC](2), float64(2), object(7), period[M](2)
memory usage: 276.3+ MB

None

In [65]:
#Calculando o ticket medio por customer_id e mês

ticket_medio_consumer = (order_rest.groupby(['customer_id', 'ano_mes_created_at'])['order_total_amount']
    .mean()
    .reset_index()
    .rename(columns={'order_total_amount': 'ticket_medio'})
)

min_order_by_consumer = (order_rest.groupby('customer_id')['minimum_order_value']
    .mean()
    .reset_index()
)

ticket_segmented = ticket_medio_consumer.merge(min_order_by_consumer, on='customer_id', how='left')

ticket_segmented = ticket_segmented.merge(consumer_merge[['customer_id', 'is_target']], on='customer_id', how='left')

ticket_segmented['ano_mes_created_at'] = ticket_segmented['ano_mes_created_at'].dt.strftime('%Y-%m')

test_ab = ['2018-12', '2019-01']
ticket_segmented = ticket_segmented[ticket_segmented['ano_mes_created_at'].isin(test_ab)]

ticket_segmented['faixa_min_order_value'] = pd.cut(ticket_segmented['minimum_order_value'],
    bins=[0, 30, 60, 100, 200, 10000],
    labels=['0-30', '30-60', '60-100', '100-200', '200+']
)

ticket_segmented_avg = (ticket_segmented.groupby(['faixa_min_order_value', 'ano_mes_created_at', 'is_target'])['ticket_medio']
    .mean()
    .reset_index()
)

display(ticket_segmented_avg.head())
display(ticket_segmented_avg.info())

/tmp/ipykernel_10656/1742656598.py:28: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

  faixa_min_order_value ano_mes_created_at is_target  ticket_medio
0                  0-30            2018-12   control     46.495257
1                  0-30            2018-12    target     46.178524
2                  0-30            2019-01   control     46.263462
3                  0-30            2019-01    target     46.068493
4                 30-60            2018-12   control     66.951697

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   faixa_min_order_value  20 non-null     category
 1   ano_mes_created_at     20 non-null     object
 2   is_target              20 non-null     object
 3   ticket_medio           20 non-null     float64
dtypes: category(1), float64(1), object(2)
memory usage: 844.0+ bytes

None

In [70]:
#Filtrando apenas o grupo target (grupo de interesse)
ticket_segmented_target = ticket_segmented_avg[ticket_segmented_avg['is_target'] == 'target']

#Resultado por gráfico
fig = px.bar(
    ticket_segmented_target,
    x='faixa_min_order_value',
    y='ticket_medio',
    color='ano_mes_created_at',
    barmode='group',
    labels={
        'faixa_min_order_value': 'Faixa de Minimum Order Value',
        'ticket_medio': 'Ticket Médio',
        'ano_mes_created_at': 'Mês'
    },
    title='Ticket Médio por Faixa de Minimum Order Value (Grupo Target) - Dez/2018 vs Jan/2019'
)

fig.show()